services:
  backend:
    container_name: node-backend
    # build:
    #   context: ./backend
    #   dockerfile: Dockerfile
    image: saiyedin786/travelmememory-prashant:backend01
      
    ports:
      - "3001:3001"
    environment:
      MONGO_URI: mongodb+srv://admin:admin@cluster0.ns7tmns.mongodb.net/travelmemory
    restart: always
    networks:
      - mynetwork

  frontend:
    container_name: react-frontend
    # build:
    #   context: ./frontend
    #   dockerfile: Dockerfile
    #   args:
    #     REACT_APP_BACKEND_URL: http://13.235.104.223:3001
    image: saiyedin786/travelmememory-prashant:frontend01
    ports:
      - "80:80"
    #environment:
      #REACT_APP_BACKEND_URL: http://backend:3001
    depends_on:
      - backend
    restart: always
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
