apiVersion: v1
kind: Secret
metadata: 
  namespace: three-tier
  name: mongo-sec
type: Opaque
data:  
  password: cGFzc3dvcmQxMjM=   #Three-Tier-Project #password123
  username: YWRtaW4= #admin