apiVersion: v1
kind: Service
metadata: 
  name: frontend-svc
  namespace: travelmemory
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  type: ClusterIP
  selector:
    role: frontend

